# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_gen import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/aimodule.v1.AiService/Predict',
                request_serializer=ai__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ai__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Prescribe = channel.unary_unary(
                '/aimodule.v1.AiService/Prescribe',
                request_serializer=ai__service__pb2.PrescribeRequest.SerializeToString,
                response_deserializer=ai__service__pb2.PrescribeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aimodule.v1.AiService/Health',
                request_serializer=ai__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PredictStream = channel.stream_stream(
                '/aimodule.v1.AiService/PredictStream',
                request_serializer=ai__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ai__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.VerifyTicket = channel.unary_unary(
                '/aimodule.v1.AiService/VerifyTicket',
                request_serializer=ai__service__pb2.VerifyTicketRequest.SerializeToString,
                response_deserializer=ai__service__pb2.VerifyTicketResponse.FromString,
                _registered_method=True)
        self.SubmitFeedback = channel.unary_unary(
                '/aimodule.v1.AiService/SubmitFeedback',
                request_serializer=ai__service__pb2.SubmitFeedbackRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SubmitFeedbackResponse.FromString,
                _registered_method=True)
        self.PredictLong = channel.unary_unary(
                '/aimodule.v1.AiService/PredictLong',
                request_serializer=ai__service__pb2.PredictLongRequest.SerializeToString,
                response_deserializer=ai__service__pb2.PredictLongResponse.FromString,
                _registered_method=True)
        self.SubmitClassificationFeedback = channel.unary_unary(
                '/aimodule.v1.AiService/SubmitClassificationFeedback',
                request_serializer=ai__service__pb2.ClassificationFeedbackRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ClassificationFeedbackResponse.FromString,
                _registered_method=True)
        self.SuggestStaff = channel.unary_unary(
                '/aimodule.v1.AiService/SuggestStaff',
                request_serializer=ai__service__pb2.SuggestStaffRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SuggestStaffResponse.FromString,
                _registered_method=True)
        self.SuggestKb = channel.unary_unary(
                '/aimodule.v1.AiService/SuggestKb',
                request_serializer=ai__service__pb2.SuggestKbRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SuggestKbResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Mirror of POST /predict
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prescribe(self, request, context):
        """Mirror of POST /prescribe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Mirror of GET /health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictStream(self, request_iterator, context):
        """Bidirectional streaming variant of Predict (server impl lands in GH-41)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyTicket(self, request, context):
        """Mirror of POST /verify-ticket — chấm điểm ticket thủ công thật/rác + dò trùng mô tả.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitFeedback(self, request, context):
        """Mirror of POST /prescribe/feedback — kỹ thuật viên phản hồi 1 prescription đã trả.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictLong(self, request, context):
        """Mirror of POST /predict/long — SOH từ chuỗi dài (L ≤ 4096 timestep) bằng model
        long-sequence (attention pooling). KHÁC Predict: 1 forward pass, KHÔNG MC-dropout,
        KHÔNG anomaly (IsolationForest chỉ train trên phân bố feature của window=30).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitClassificationFeedback(self, request, context):
        """Mirror of POST /predict/feedback — kỹ thuật viên chấm lại phân loại AI đã đưa ra.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestStaff(self, request, context):
        """Mirror of POST /suggest/staff — xếp hạng nhân viên phù hợp xử lý ticket.
        Human-in-the-loop: AI chỉ gợi ý + nêu lý do, Manager quyết định giao cho ai.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestKb(self, request, context):
        """Mirror of POST /suggest/kb — xếp hạng bài viết KB để tham khảo khi sửa chữa.
        Human-in-the-loop: kỹ thuật viên bấm áp dụng thì BE mới tạo TicketKbReference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ai__service__pb2.PredictRequest.FromString,
                    response_serializer=ai__service__pb2.PredictResponse.SerializeToString,
            ),
            'Prescribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Prescribe,
                    request_deserializer=ai__service__pb2.PrescribeRequest.FromString,
                    response_serializer=ai__service__pb2.PrescribeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__service__pb2.HealthRequest.FromString,
                    response_serializer=ai__service__pb2.HealthResponse.SerializeToString,
            ),
            'PredictStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PredictStream,
                    request_deserializer=ai__service__pb2.PredictRequest.FromString,
                    response_serializer=ai__service__pb2.PredictResponse.SerializeToString,
            ),
            'VerifyTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyTicket,
                    request_deserializer=ai__service__pb2.VerifyTicketRequest.FromString,
                    response_serializer=ai__service__pb2.VerifyTicketResponse.SerializeToString,
            ),
            'SubmitFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFeedback,
                    request_deserializer=ai__service__pb2.SubmitFeedbackRequest.FromString,
                    response_serializer=ai__service__pb2.SubmitFeedbackResponse.SerializeToString,
            ),
            'PredictLong': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictLong,
                    request_deserializer=ai__service__pb2.PredictLongRequest.FromString,
                    response_serializer=ai__service__pb2.PredictLongResponse.SerializeToString,
            ),
            'SubmitClassificationFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitClassificationFeedback,
                    request_deserializer=ai__service__pb2.ClassificationFeedbackRequest.FromString,
                    response_serializer=ai__service__pb2.ClassificationFeedbackResponse.SerializeToString,
            ),
            'SuggestStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestStaff,
                    request_deserializer=ai__service__pb2.SuggestStaffRequest.FromString,
                    response_serializer=ai__service__pb2.SuggestStaffResponse.SerializeToString,
            ),
            'SuggestKb': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestKb,
                    request_deserializer=ai__service__pb2.SuggestKbRequest.FromString,
                    response_serializer=ai__service__pb2.SuggestKbResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aimodule.v1.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aimodule.v1.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/Predict',
            ai__service__pb2.PredictRequest.SerializeToString,
            ai__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prescribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/Prescribe',
            ai__service__pb2.PrescribeRequest.SerializeToString,
            ai__service__pb2.PrescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/Health',
            ai__service__pb2.HealthRequest.SerializeToString,
            ai__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aimodule.v1.AiService/PredictStream',
            ai__service__pb2.PredictRequest.SerializeToString,
            ai__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/VerifyTicket',
            ai__service__pb2.VerifyTicketRequest.SerializeToString,
            ai__service__pb2.VerifyTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/SubmitFeedback',
            ai__service__pb2.SubmitFeedbackRequest.SerializeToString,
            ai__service__pb2.SubmitFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/PredictLong',
            ai__service__pb2.PredictLongRequest.SerializeToString,
            ai__service__pb2.PredictLongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitClassificationFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/SubmitClassificationFeedback',
            ai__service__pb2.ClassificationFeedbackRequest.SerializeToString,
            ai__service__pb2.ClassificationFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/SuggestStaff',
            ai__service__pb2.SuggestStaffRequest.SerializeToString,
            ai__service__pb2.SuggestStaffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestKb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aimodule.v1.AiService/SuggestKb',
            ai__service__pb2.SuggestKbRequest.SerializeToString,
            ai__service__pb2.SuggestKbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
